apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: aggregate-secretdefinitions-admin-edit
rules:
- apiGroups:
    - secrets-manager.tuenti.io
  resources:
    - secretdefinitions
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection